name: build

on:
  push:
    branches:
      - master
      - development
      - task/**
      - bugfix/**
      - feature/**
  pull_request:
    branches:
      - master
      - development
      - task/**
      - bugfix/**
      - feature/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install/Update dependencies
      run: composer update --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test
